project: combination
model_dir: /home/eric.moreno/gwak2/gwak/output
output_dir: /home/eric.moreno/gwak2/gwak/output/export
clean: True
background_batch_size: 2 # Fixed setting Channel 1 PSD estimeter Channel 2 Processing strain data 
stride_batch_size: 256
num_ifos: 2
gwak_instances: 15
platform: TORCHSCRIPT
# platform: ONNX
psd_length: 64
kernel_length: 0.09765625
fduration: 1
fftlength: 2
sample_rate: 2048
preproc_instances: 1
inference_sampling_rate: 1
# inference_sampling_rate: 10.24